; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sms-uart-esp32]
platform = espressif32
board = lolin32
framework = arduino
;upload_port = /dev/cu.usbserial-018BE5A8
;monitor_port = /dev/cu.usbserial-018BE5A8

;upload_port = /dev/cu.usbserial-01DA68DF
;monitor_port = /dev/cu.usbserial-01DA68DF

monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"sms-uart-esp32\"
	-D SHP_HB_LED_MODE=hbLEDMode_RGB
	-D SHP_HB_LED_PIN=4
	-D SHP_DISABLE_CAN_ROUTER
	-I ../libs
	-I ../../../.platformio/lib/PN532/PN532
	-I ../../../.platformio/lib/PN532/PN532_I2C
	-I ../../../.platformio/lib/PN532/PN532_HSU
lib_deps =
	bertmelis/esp32DHT@^1.0.1
	adafruit/Adafruit BME280 Library@^2.1.2
	claws/BH1750@^1.2.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.19.3
	paulstoffregen/OneWire@^2.3.6
	milesburton/DallasTemperature@^3.9.1
	teckel12/NewPing@^1.9.4
	adafruit/Adafruit NeoPixel@^1.10.4
	kitesurfer1404/WS2812FX@^1.4.0
	ncmreynolds/ld2410
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit SHT4x Library@^1.0.5

[env:sms-uart-esp32S3]
platform_packages =
    toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"sms-uart-esp32s3\"
	-D SHP_HB_LED_MODE=hbLEDMode_RGB
	-D SHP_HB_LED_PIN=4
	-D SHP_DISABLE_CAN_ROUTER
	-I ../libs
	-I ../../../.platformio/lib/PN532/PN532
	-I ../../../.platformio/lib/PN532/PN532_I2C
	-I ../../../.platformio/lib/PN532/PN532_HSU
lib_deps =
	bertmelis/esp32DHT@^1.0.1
	adafruit/Adafruit BME280 Library@^2.1.2
	claws/BH1750@^1.2.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.2
	paulstoffregen/OneWire@^2.3.6
	milesburton/DallasTemperature@^3.9.1
	teckel12/NewPing@^1.9.4
	adafruit/Adafruit NeoPixel@^1.10.4
	kitesurfer1404/WS2812FX@^1.4.0
	ncmreynolds/ld2410
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit SHT4x Library@^1.0.5
