; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps_default =
	bblanchon/ArduinoJson@6.17.3
	knolleary/PubSubClient@^2.8
	paulstoffregen/OneWire@^2.3.6
	milesburton/DallasTemperature@^3.9.1
	teckel12/NewPing@^1.9.4
	adafruit/Adafruit NeoPixel@^1.10.4
	kitesurfer1404/WS2812FX@^1.4.0
	bertmelis/esp32DHT@^1.0.1
	adafruit/Adafruit BME280 Library@^2.1.2
	claws/BH1750@^1.2.0
	WiFi
	ncmreynolds/ld2410
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit SHT4x Library@^1.0.5
	adafruit/Adafruit BME680 Library@^2.0.5

[env:epd-esp32-wifi-GxEPD2_750c]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_750c
	-D SHP_WIFI
	-D SHP_WIFI_MANAGER
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32S3-wifi-GxEPD2_750c]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_750c
	-D SHP_EPD_BOARD_M25
	-D BOARD_HAS_PSRAM
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D SHP_WIFI
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32-wifi-GxEPD2_750c_Z08]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_750c_Z08
	-D SHP_WIFI
	-D SHP_WIFI_MANAGER
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32S3-wifi-GxEPD2_750c_Z08]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_750c_Z08
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D SHP_WIFI
	-D SHP_EPD_BOARD_M25
	-D BOARD_HAS_PSRAM
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32-wifi-GxEPD2_266c_GDEY0266F51H]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_266c_GDEY0266F51H
	-D SHP_WIFI
	-D SHP_WIFI_MANAGER
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32S3-wifi-GxEPD2_583_GDEQ0583T31]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_BW
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_583_GDEQ0583T31
	-D SHP_WIFI
	-D SHP_EPD_BOARD_M25
	-D BOARD_HAS_PSRAM
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D MQTT_MAX_PACKET_SIZE=2048
	-D SHP_HB_LED_MODE=hbLEDMode_BINARY
	-D SHP_HB_LED_PIN=2
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32-wifi-GxEPD2_730c_GDEY073D46]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_7C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_730c_GDEY073D46
	-D SHP_WIFI
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4


[env:epd-esp32S3-wifi-GxEPD2_730c_GDEY073D46]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_7C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_730c_GDEY073D46
	-D SHP_EPD_BOARD_M25
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D SHP_WIFI
	-D BOARD_HAS_PSRAM
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4


[env:epd-esp32S3-wifi-GxEPD2_730c_GDEP073E01]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_7C
	-D GxEPD2_DRIVER_CLASS=GxEPD2_730c_GDEP073E01
	-D SHP_EPD_BOARD_M25
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D SHP_WIFI
	-D BOARD_HAS_PSRAM
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4


[env:epd-esp32-wifi-GxEPD2_420c]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_420c
	-D SHP_WIFI
	-D SHP_WIFI_MANAGER
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32S3-wifi-GxEPD2_1248c]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_1248c
	-D SHP_EINK_PWR_PIN=GPIO_NUM_48
	-D SHP_WIFI
	-D BOARD_HAS_PSRAM
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32-wifi-GxEPD2_1248c]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_echo = yes
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_3C
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_1248c
	-D SHP_EINK_PWR_PIN=GPIO_NUM_12
	-D SHP_WIFI
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32-wifi-GxEPD2_1248]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -DBOARD_HAS_PSRAM
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D GxEPD2_DISPLAY_CLASS=GxEPD2_BW
	-D GxEPD2_DRIVER_CLASS=SHP_GxEPD2_1248
	-D SHP_EINK_PWR_PIN=GPIO_NUM_12
	-D SHP_WIFI
	-D SHP_WIFI_MANAGER
	-D MQTT_MAX_PACKET_SIZE=2048
	-I ../libs
lib_deps = ${common.lib_deps_default}
	zinggjm/GxEPD2@^1.6.4

[env:epd-esp32S3-wifi-133S6]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200
monitor_echo = yes
build_flags =
	-D SHP_DEVICE_TYPE=\"iot-box-epd-wifi-esp32\"
	-D SHP_POWER_BATT_CHARGER=SHP_USB_CHIP_BQ25896
	-D SHPD_DRIVER_CLASS=SEPD_133S6
	-D SHP_EPD_BOARD_M60
	-D SHP_EINK_PWR_PIN=GPIO_NUM_9
	-D SHP_WIFI
	-D BOARD_HAS_PSRAM
	-D MQTT_MAX_PACKET_SIZE=2048
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-I ../libs
lib_deps = ${common.lib_deps_default}

